// Generated by CoffeeScript 1.4.0
var a, document, idExpr, simpleExpr, slice, string, tagExpr, window, xui;

void 0;

xui;


window = this;

string = new String('string');

document = window.document;

simpleExpr = /^#?([\w-]+)$/;

idExpr = /^#/;

tagExpr = /<([\w:]+)/;

slice = function(e) {
  return [].slice.call(e, 0);
};

try {
  a = slice(document.documentElement.childNodes)[0].nodeType;
} catch (e) {
  slice = function(e) {
    var i, ret, _i, _len, _ref;
    ret = [];
    _ref = e[i];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      ret.push(e[i]);
    }
    return ret;
  };
}

window.x$ = window.xui = xui = function(q, context) {
  return new xui.fn.find(q, context);
};
